version: "3"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
    ports:
      - 3000:3000

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=mtelec
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - '27017:27017'
    restart: always

volumes:
  mongodb_data: